laplace:
	g++ -fsanitize=address -fsanitize=leak -fsanitize=undefined  laplace.cpp
laplace2:
	g++ -fsanitize=address -fsanitize=leak -fsanitize=undefined  laplace2.cpp
laplace3:
	g++ -fsanitize=address -fsanitize=leak -fsanitize=undefined  laplace3.cpp
onda:
	g++ -fsanitize=address -fsanitize=leak -fsanitize=undefined  onda.cpp
clean:
	rm -f *.dat *.txt *.gp
